language: objective-c
sudo: false
xcode_workspace: Hangulize.xcworkspace
xcode_scheme: Hangulize
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11
osx_image: xcode11.2
install:
  - gem update cocoapods
  - pod install
  - brew install swiftformat
before_script:
  - swiftformat --lint .
