language: objective-c
sudo: false
xcode_workspace: Hangulize.xcworkspace
osx_image: xcode11
install:
  - gem update cocoapods
  - pod install
  - brew install swiftformat
script:
  - swiftformat --lint .
  - set -o pipefail && xcodebuild -workspace Hangulize.xcworkspace -scheme Hangulize -sdk iphoneos -destination platform\=iOS\ Simulator,OS\=13.2.2,name\=iPhone\ 11 build test | xcpretty
